M48
; DRILL file {KiCad (6.0.6-0)} date Sunday, November 06, 2022 at 01:19:20 am
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-06T01:19:20-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.54Y-3.64
X3.55Y-5.35
X3.94Y-1.08
X5.1Y-4.46
T0
M30
